### ISSUE TITLE
Available as NPM Package

### ISSUE THREAD

**Issue by christophrumpel** [tillkruss/alfred-laravel-docs#10]
First thanks for the great workflow!

It would be a nice addition if I could install this package via NPM like this workflow here https://github.com/nikersify/alfred-polyglot.

This way I could it install with my Dotfiles automatically :-)

Greets

**Comment by tillkruss** [comment]
Interesting. I guess all we need is a `package.json`?

What does your `alfred-polyglot` install command look like?

**Comment by christophrumpel** [comment]
I think so :-) https://www.alfredforum.com/topic/11235-polyglot-yet-another-google-translate-workflow/

**Comment by tillkruss** [comment]
Seems like it needs a lot of NPM packages. How do you feel about submitting a PR?

**Comment by christophrumpel** [comment]
Actually, I have no idea about NPM packages, but I'll try to take a look :-)
