### ISSUE TITLE
Missing Laravel.Docs.alfredworkflow for v0.2.3

### ISSUE THREAD

**Issue by vintagesucks** [tillkruss/alfred-laravel-docs#12]
Hi! There is no `Laravel.Docs.alfredworkflow` for v0.2.3 attached to [the GitHub Release](https://github.com/tillkruss/alfred-laravel-docs/releases/tag/v0.2.3). The download link in the README is broken, too.

**Comment by tillkruss** [comment]
I'll fix that!

**Comment by tillkruss** [comment]
LMK if the asset works for you!
