### ISSUE TITLE
Help fot Ulauncher configuration

### ISSUE THREAD

**Issue by max-bertinetti** [tillkruss/alfred-laravel-docs#16]
Hi @tillkruss . Times ago I have a Mac with Alfredapp. Now I'm using a PC with Linux and I'm using [Ulauncher](http://ulauncher.io/).

I find a way to have the search work for [Pest](https://github.com/AlexMartinFR/alfred-pestphp-docs) and [Livewire](https://github.com/AlexMartinFR/alfred-livewire-docs) but I cannot "convert" your to work.

I'm using this data:

```  
...
    "laravel": {
        "name": "Laravel",
        "description": "The PHP Framework for Web Artisans",
        "icon": "images/docs/laravel.jpg",
        "algolia_index": "docs",
        "algolia_application_id": "8BB87I11DE",
        "algolia_api_key": "8e1d446d61fce359f69cd7c8b86a50de",
        "url": "https://laravel.com/docs/7.x/"
    },
    "livewire": {
        "name": "Livewire",
        "description": "Livewire is a full-stack framework that makes building dynamic interfaces simple, without leaving the comfort of Laravel.",
        "icon": "images/docs/livewire.jpg",
        "algolia_index": "livewire-framework",
        "algolia_application_id": "BH4D9OD16A",
        "algolia_api_key": "cec0554d960fa30b4b0b610f372a8636",
        "url": "https://laravel-livewire.com/docs/quickstart/"
    },
...
```
Can you give me some hints?

**Comment by tillkruss** [comment]
If you ask an exact question, I might be able to help.

**Comment by max-bertinetti** [comment]
Is the data correct?

**Comment by tillkruss** [comment]
What data?

**Comment by max-bertinetti** [comment]
Algolia data that I'm passing

**Comment by tillkruss** [comment]
I don't know.

**Comment by max-bertinetti** [comment]
Sorry @tillkruss to bother you, but I think you can help me, only I don't tell exactly what I need to understand: I'm using a plugin that works like yours for call sites that has docs working with Algolia.

Some are already comfigured, but I like to have also laravel, pest and livewire.
I take the data for configuration for pest and livewire from other plugin for Alfred exactly like yours.

The configuration for Laravel is from yours:

```
$workflow = new Workflow;
$parsedown = new Parsedown;
$algolia = new Algolia('8BB87I11DE', '8e1d446d61fce359f69cd7c8b86a50de');

AlgoliaUserAgent::addSuffixUserAgentSegment('Alfred Workflow', '0.2.3');

$index = $algolia->initIndex('docs');
$search = $index->search($query, ['tagFilters' => $branch ?: 'master']);
$results = $search['hits'];
```

The became in my configuration:

```
 "algolia_index": "docs",
"algolia_application_id": "8BB87I11DE",
"algolia_api_key": "8e1d446d61fce359f69cd7c8b86a50de",
"url": "https://laravel.com/docs/7.x/"
```
Where you take the data above(algolia_application_id, algolia_apy_key, index....)?

I make some error transporting your data that I cannot see?

**Comment by tillkruss** [comment]
I got those Algolia credentials from @taylorotwell and laravel.com.

Make sure you ask for permission from Taylor before using them.
