### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by beebmx** [tillkruss/alfred-laravel-docs#17]
Hi, I don't know if its only me, but I changed the branch to `8.x` and the results is always empty.

Am I doing it right?

BTW, thanks for this, it's an awesome tool.

**Comment by dimitri-koenig** [comment]
You can use "latest" as branch value, which resolves to 8.x

**Comment by marcusmoore** [comment]
For anyone else that was wondering by `latest` might not be working for them, I was running `v0.2.2` and `latest` was made available in `v0.2.4`: https://github.com/tillkruss/alfred-laravel-docs/releases

Might be as easy as an update 😄

**Comment by tillkruss** [comment]
@beebmx: What version of the workflow are you running?

**Comment by beebmx** [comment]
I'm running `v0.2.3`

**Comment by beebmx** [comment]
I'm upgrade to `v0.2.4` but it's the same.

**Comment by tillkruss** [comment]
This is indeed broken. I'll tag 0.3.0 later.

**Comment by tillkruss** [comment]
packal.org is such garbage, is there anything else out there to distribute Alfred packages?
