### ISSUE TITLE
Results are ambiguous with a minimal Alfred theme

### ISSUE THREAD

**Issue by thecrypticace** [tillkruss/alfred-laravel-docs#2]
This is what I see when I invoke the docs. It'd be nice to be able to configure this somehow.

<img width="594" alt="screen shot 2018-07-31 at 09 26 01" src="https://user-images.githubusercontent.com/614993/43462647-a741c65a-94a4-11e8-9d20-a9145c4525cd.png">

**Comment by tillkruss** [comment]
Could you search for other terms, such a "unit"? As a test, not a fix 😉

**Comment by thecrypticace** [comment]
Here you go:

<img width="594" alt="screen shot 2018-07-31 at 10 02 20" src="https://user-images.githubusercontent.com/614993/43464330-d6900b66-94a8-11e8-9738-9461ff551380.png">

**Comment by tillkruss** [comment]
How are you getting that minimal theme? Is it a theme or an option in alfred?

<img width="596" alt="screen shot 2018-07-31 at 7 14 33 am" src="https://user-images.githubusercontent.com/665029/43465085-6eb586cc-9491-11e8-98ff-21dbed37dd71.png">

**Comment by thecrypticace** [comment]
My theme is custom but this is an option in the appearance section.

Appearance > Options (bottom left corner) > "Show Result Subtext: Only for Alternative Actions"

I have the result subtext turned off. I _can_ turn it on I just prefer to have it off.

<img width="1212" alt="screen shot 2018-07-31 at 10 19 51" src="https://user-images.githubusercontent.com/614993/43465513-7f8b773a-94ab-11e8-91a4-e41f34978c81.png">

**Comment by tillkruss** [comment]
Thanks for the details! Fixed it in f233b21a835fd704ce0be027b22bc365fd003a2a. I'll push an update later today.
