### ISSUE TITLE
Alfred 3.x compatibility issue

### ISSUE THREAD

**Issue by ivanhoe011** [tillkruss/alfred-laravel-docs#20]
Not sure if this is a regression bug, or you removed the support for Alfred 3 and just forgot to update the readme files, but I was unable to install the version from the current master branch. Alfred 3.8.6 complains that the workflow isn't compatible. 

I've next tried installing the previous version with the tag v0.2.4 and it worked just fine with my Alfred 3.

**Comment by tillkruss** [comment]
I'm running Alfred 4.6. Can you post the error message you're seeing?

**Comment by ivanhoe011** [comment]
This is how it looks in Alfred 3.8.6. Workflow gets added to the list in the sidebar, but instead of the details in the right hand panel you get this:
<img width="442" alt="Screenshot 2021-11-02 at 13 40 42" src="https://user-images.githubusercontent.com/1836505/139848893-9b17280c-2da0-4137-98dc-c557c74ad062.png">

As I mentioned already, the previous version (0.2.4) works fine, this is just a regression in the current master.

**Comment by tillkruss** [comment]
@ivanhoe011: I'm likely only supporting the latest version of Alfred. If you want to submit a PR that ensures support for v3 and v4 great 👍

**Comment by neoighodaro** [comment]
I don't know if I should piggyback on this thread, however it does not work for me. It used to work but now after `ld` when I type anything it switches to Google search

<img width="589" alt="Screenshot 2021-11-02 at 20 33 53" src="https://user-images.githubusercontent.com/807318/139940189-d345e417-50b6-4bc6-af9e-f33802cffd3b.png">

**Comment by nathanjansen** [comment]
> I don't know if I should piggyback on this thread, however it does not work for me. It used to work but now after `ld` when I type anything it switches to Google search
> 
> <img alt="Screenshot 2021-11-02 at 20 33 53" width="589" src="https://user-images.githubusercontent.com/807318/139940189-d345e417-50b6-4bc6-af9e-f33802cffd3b.png">

Some problem here :) Using Macbook Pro M1 (Max) 2021

**Comment by patrickomeara** [comment]
I'm 90% sure @neoighodaro and @nathanjansen's issue started after upgrading to Monterey.

It is unrelated to the 3.x problem this issue started with.

**Comment by patrickomeara** [comment]
After further digging it looks like it's an issue across other workflows as well

![image](https://user-images.githubusercontent.com/571773/140194299-8cd540aa-f0ba-4c88-b96c-7d348166fb37.png)

![image](https://user-images.githubusercontent.com/571773/140194328-609b24e5-6e63-4d90-bd2b-63a1e9b58af0.png)

**Comment by nathanjansen** [comment]
That makes sense :) Thank you for digging further into this @patrickomeara.
I will report a bug at Alfred.

**Comment by tillkruss** [comment]
Are you all on macOS 12.0?

**Comment by neoighodaro** [comment]
> Are you all on macOS 12.0?

I'm on Monterey yes

**Comment by kennyhorna** [comment]
> After further digging it looks like it's an issue across other workflows as well
> 
> ![image](https://user-images.githubusercontent.com/571773/140194299-8cd540aa-f0ba-4c88-b96c-7d348166fb37.png)
> 
> ![image](https://user-images.githubusercontent.com/571773/140194328-609b24e5-6e63-4d90-bd2b-63a1e9b58af0.png)

I have the same issue on macOS Monterey (Alfred 4.6)

**Comment by mojowill** [comment]
On Monterey as well.

PHP has been removed from Mac OS Monterey (https://developer.apple.com/forums/thread/681907) so on a fresh install of this workflow I was seeing:

`Code 127: /bin/bash: php: command not found`

I updated the script to use `/opt/homebrew/bin/php` from the language dropdown (it was set to `/bin/bash`) and updated the script to remove the php call `laravel.php "{query}"`.

There is now a new error:

```
[08:37:52.483] Laravel Docs[Script Filter] Queuing argument 'blade'
[08:37:52.511] Laravel Docs[Script Filter] Script with argv '(null)' finished
[08:37:52.520] ERROR: Laravel Docs[Script Filter] Code 255: Parse error: syntax error, unexpected double-quoted string "blade" in Command line code on line 1
[08:37:52.521] ERROR: Laravel Docs[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:
Parse error: syntax error, unexpected double-quoted string "blade" in Command line code on line 1
```

**Comment by tillkruss** [comment]
I think they fundamentally changed how workflows are executed.

**Comment by andrewminion-luminfire** [comment]
Perhaps it’s an Intel vs. Apple Silicon change: Homebrew installed php on macOS 12 will be found in either `/opt/homebrew/bin/php` (Apple Silicon) or `usr/local/bin/php` (Intel)
