### ISSUE TITLE
Alfred 4 on Mac Monterey on M1 MacBook Pro

### ISSUE THREAD

**Issue by AstroBoy269** [tillkruss/alfred-laravel-docs#21]
Is anyone having issues with the the workflow?  Just setting up a new M1Max MacBook Pro with Alfred 4 and this workflow exhibits an odd behavior.  When you 'wake Alfred' and type "ld" you see what you'd expect in the Alfred query box 
<img width="578" alt="Screen Shot 2021-10-30 at 6 37 32 PM" src="https://user-images.githubusercontent.com/10376292/139560351-dfb67dd6-d11e-4799-ac35-139c160558f0.png">
 
But just as soon as you start typing the query, Alfred thinks you're typing in a regular search query? see this screen:

<img width="577" alt="Screen Shot 2021-10-30 at 6 37 48 PM" src="https://user-images.githubusercontent.com/10376292/139560447-b6762a94-cddf-4d90-8d80-f42fd1514139.png">
 
I'm not 100% the best way to describe this issue so any suggestions would be appreciated.  

So this is Monterey 12.0.1 on a MacBook Pro with the M1Max chip.  Not sure any of that makes a difference.  I have several workflows that exhibit similar behavior.  I've confirmed that the php executable is correct.  This is what the configuration screen looks like: 

<img width="787" alt="Screen Shot 2021-10-30 at 6 47 52 PM" src="https://user-images.githubusercontent.com/10376292/139560518-e77a2f1c-320e-4a24-9947-64e97e4bc8a8.png">

**Comment by AstroBoy269** [comment]
So I think I just figured this out.  I use PHP 7.4 as installed by Homebrew and it didn't or doesn't anymore install in /usr/local/bin but instead installs into /opt/homebrew/bin/php .  I changed the workflow as follows and it's working now.  Plus now at least I understand a little more about debugging Workflows
<img width="787" alt="Screen Shot 2021-10-30 at 6 59 33 PM" src="https://user-images.githubusercontent.com/10376292/139560758-962ee6fb-283c-4b60-9788-d42d98475a35.png">
.

**Comment by AstroBoy269** [comment]
I think I fixed my own problem.

**Comment by tillkruss** [comment]
@AstroBoy269: It might be nice to auto-detect the PHP binary. Can you send a PR?

**Comment by dimsav** [comment]
Sorry to bring this back. 

I'm experiencing the same issue on MacOS 12.3.1

<img width="221" alt="CleanShot 2022-04-11 at 10 50 22@2x" src="https://user-images.githubusercontent.com/1785686/162689927-ee0a7131-6da7-4dba-b79d-d1d0e3e13151.png">

Alfred version: 4.6.4

Laravel Docs: v0.3.3


<img width="788" alt="CleanShot 2022-04-11 at 10 53 18@2x" src="https://user-images.githubusercontent.com/1785686/162690350-0e4f6faa-a6d1-4967-8212-119d8742b8cf.png">

<img width="753" alt="CleanShot 2022-04-11 at 10 53 51@2x" src="https://user-images.githubusercontent.com/1785686/162690450-6ff70174-ae78-462d-b5ab-26542c824ea9.png">


Any idea why Alfred skips laravel docs? 

<img width="719" alt="CleanShot 2022-04-11 at 10 54 44@2x" src="https://user-images.githubusercontent.com/1785686/162690598-a945ba7c-f1a8-4b9a-89db-adebbd08ef9a.png">

<img width="715" alt="CleanShot 2022-04-11 at 10 55 06@2x" src="https://user-images.githubusercontent.com/1785686/162690656-137c76d6-0b59-4ea9-9a61-30c3242ba077.png">

Thank you!

**Comment by tillkruss** [comment]
@dimsav: Post your workflow debug logs.

<img width="1355" alt="Screen Shot 2022-04-11 at 8 44 11 AM" src="https://user-images.githubusercontent.com/665029/162779219-ba3682b4-f3ec-475c-81cc-42aa04b508d6.png">

**Comment by dimsav** [comment]
```
[20:00:17.530] Logging Started...
[20:00:27.144] Laravel Docs[Script Filter] Queuing argument 's'
[20:00:27.197] Laravel Docs[Script Filter] Script with argv '(null)' finished
[20:00:27.200] ERROR: Laravel Docs[Script Filter] Code 255: Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.28. in /Users/user123/Dropbox/Mac Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4B58618E-9365-4BBC-A19B-18DA87B62356/vendor/composer/platform_check.php on line 24
[20:00:27.201] ERROR: Laravel Docs[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.28. in /Users/user123/Dropbox/Mac Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4B58618E-9365-4BBC-A19B-18DA87B62356/vendor/composer/platform_check.php on line 24
```

How can we use this very nice alfred workflow when we have php v7.4 installed? Thanks!

**Comment by tillkruss** [comment]
Fix your local Composer installation.

```
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0".
You are running 7.4.28.
```

**Comment by dimsav** [comment]
If anyone has faced the same issue do the following because they have multiple versions of php installed: 

- Install php 8 via brew. 
- Then check the bin path by running `brew list php`

For example:

![CleanShot 2022-04-14 at 20 49 04@2x](https://user-images.githubusercontent.com/1785686/163448450-d602ceb5-7872-405b-a819-f18c92988b41.png)

- Then open alfred workflows and edit the script for laravel docs, by entering this: 

```
/opt/homebrew/Cellar/php/8.1.3_1/bin/php laravel.php "{query}"
```

(replace with your php bin path)

**Comment by tillkruss** [comment]
The correct homebrew path is: `brew --prefix php`

**Comment by ivanhoe011** [comment]
I had a similar problem on Sonoma, but for me the path to php was OK. After further investigation it turned out the composer.lock (in the workflow dir) had requirements that couldn't be satisfied (I need php 7.3 for work, don't ask). Fixed it by removing the entire vendor dir and composer.lock and running `composer install` (probably just `composer update` would work the same, but I prefer having a clean state to start with).
