### ISSUE TITLE
Laravel Herd support

### ISSUE THREAD

**Issue by nexxai** [tillkruss/alfred-laravel-docs#26]
Just tried to install this with the Laravel Herd-installed PHP as the only executable on my system and it wouldn't work until I:

1. Opened Alfred
2. Went to the Workflows section
3. Selected the Laravel Docs workflow
4. Doubleclicked the `ld` Script Filter
5. Added the following `elif` to the list:

```sh
elif [ -f "/Users/nexxai/Library/Application Support/Herd/bin//php" ]; then
    "/Users/nexxai/Library/Application Support/Herd/bin//php" laravel.php "{query}"
```

NOTE: You *cannot* use a `~` symbol; the full path must be completed spelled out.

After that, the `ld` workflow worked perfectly.

Just leaving this here for anyone else who has this issue.

**Comment by drbyte** [comment]
You can use `$HOME` instead of `~`, like this:

```sh
elif [ -f "$HOME/Library/Application Support/Herd/bin/php" ]; then
    "$HOME/Library/Application Support/Herd/bin/php" laravel.php "{query}"
fi
```

**Comment by nexxai** [comment]
...oh my god. lol

Thank you.  Will submit PR momentarily.
