### ISSUE TITLE
Publishing your credentials

### ISSUE THREAD

**Issue by mehranhadidi** [tillkruss/alfred-laravel-docs#5]
You are publishing your Algolia credentials to the git. 

Have a good day

**Comment by tillkruss** [comment]
Yep, it's intentional.

**Comment by intrepidws** [comment]
@tillkruss I'm interested in trying to make something like this, but for Bootstrap. I'm trying to figure out exactly how you're doing this. Do you have your own Algolia account with an index setup for the Laravel docs? Do you need to maintain your own version of the Laravel docs to do this?

**Comment by tillkruss** [comment]
@intrepidws: It's @taylorotwells Algolia account that powers the docs search on laravel.com

**Comment by intrepidws** [comment]
@tillkruss Aaah, OK that explains it. Thanks for the explanation.
