### ISSUE TITLE
Is there a trick to getting Quick Look to work?

### ISSUE THREAD

**Issue by EricBusch** [tillkruss/alfred-laravel-docs#9]
Thanks for the great Alfred Workflow!

When I click [shift] or command Y I don't get a preview of the webpage. I just see the Chrome icon.

Any ideas how to get a preview?

Thanks!

<img width="602" alt="screen shot 2018-08-05 at 8 56 08 am" src="https://user-images.githubusercontent.com/12106436/43686067-848a500e-988d-11e8-847d-3fff9737831f.png">

**Comment by tillkruss** [comment]
`<shift>` doesn't do anything for me, but `⌘Y` works for me. Maybe something is up with your Alfred setup?

**Comment by EricBusch** [comment]
Maybe it's my older version of Mac OS. I'll check with Alfred.

Thanks again!
Eric

**Comment by EricBusch** [comment]
Just a quick update on this. I heard back from Alfred and this is what they said:

> This is a bug in El Capitan, and Apple have fixed this in newer versions of macOS - but I don't believe they've retrospectively fixed it in El Capitan, only in the newer operating systems.

> There's a thread in our forum, and we've reported it to Apple as well:
https://www.alfredforum.com/topic/11413-lost-ability-to-quicklook-urls-in-macos-1012-bug-in-macos-sierra/

So for anyone else having this issue, it's related to your version of Mac OS, not Alfred.

**Comment by tillkruss** [comment]
Thanks for the followup!
